### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by enis-memic** [jeanbuhendwa/portfolio-website#12]
## Request changes :recycle: 

![Screenshot from 2023-01-26 08-30-41](https://user-images.githubusercontent.com/118063058/214780387-4a3c841b-7b49-404f-9612-456915cec992.png)

- Would you please try to make corrections of the padding on the icons above headings

![Screenshot from 2023-01-26 08-32-35](https://user-images.githubusercontent.com/118063058/214780540-fc9a6943-f6ec-4d1e-9370-8b550d52cbd4.png)

- Please make sure you applied the same font-family to the both inputs and text-area

Happy coding! :smile:

**Comment by jeanbuhendwa** [comment]
Thank you for the feedback
