### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by MuhammadUsmanAslam** [jeanbuhendwa/portfolio-website#22]
- Good use of semantic tags 👏 
- I suggest you look at the alignment of buttons in the modal of the desktop version highlighted in the screenshot.

![1](https://user-images.githubusercontent.com/26440637/222359603-a2d3ac8b-6ae2-494a-9935-0be1117f151d.jpg)
- `button` needs to be wrapped inside `li` https://github.com/jeanbuhendwa/portfolio-website/blob/622fa73964fe3ad83027c198b2fe7249e49cc6ed/index.html#L30

**Comment by jeanbuhendwa** [comment]
Fixed the issue. Thanks
