### ISSUE TITLE
Reviewed issues on your portfolio by the Morning Session Team

### ISSUE THREAD

**Issue by stephenkati** [jeanbuhendwa/portfolio-website#8]
**Amazing work on your responsive design**

You did an outstanding job this week coming up with a _responsive web design_ for your portfolio.
Our morning session team found a few issues when changed could make your design look even more beautiful.

- [ ] Make sure you have the correct **icons** for your social media contact
- [ ] Make sure the **width** for your _cards_ is consistent in all screen sizes
- [ ] Please use the right **width,** **padding** and **margins** in the **"see projects"** section for the _languages_ , _frameworks_ and _skills_ for all screens.
- [ ] It was noticed that you have not given the _icons_ some **top margin**,also the icons are not on the same line like that of the Figma design.
![Screenshot 2023-01-20 105947](https://user-images.githubusercontent.com/47294794/213651552-29ef18ea-2d21-4740-b24b-fe8643fe10a6.png)

**Comment by jeanbuhendwa** [comment]
Thanks for the feedback, I have worked on the issue
